name: Fetch Stablecoins

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-stablecoins:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install ts-node globally
        run: npm install -g ts-node

      - name: Run fetchStablecoins
        run: ts-node ./prisma/seed.ts
