name: Fetch Stablecoins

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-stablecoins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Prisma seed
        run: npx prisma db seed
